title: MediaPipe4U Doc
lang: zh-cn
description: 基于 MediaPipe 的 UnrealEngine 动补插件

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

